version: "3"

services:
  ##################################################################################
  # ZOOKEEPER - KAKFA CONTROL                                                      #
  ##################################################################################
  zookeeper:
    image: zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    networks:
      - elastic
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_CLIENT_PORT=2181
      #- ZOO_SERVERS: server.1=zookeeper:2888:3888
    volumes:
      - /tmp/zookeeper/data:/data
      - /tmp/zookeeper/datalog:/datalog
      - ./zookeeper/conf/zoo.cfg:/conf/zoo.cfg
      
  ##################################################################################
  # KAFKA MAIN BROKER PROCESSOR                                                    #
  ##################################################################################
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: broker
    container_name: broker
    networks:
      - elastic
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      #- KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      #- KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_DOCKER_INTERNAL://broker:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_DOCKER_INTERNAL
      - KAFKA_LOG4J_LOGGERS="kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"

    volumes:
      - /tmp/kafka/data:/var/lib/kafka/data
      - ./tests:/usr/bin/tests
    depends_on:
      - zookeeper  

  ##################################################################################
  # ELASTICSEARCH NODE                                                             #
  ##################################################################################
  elasticsearch:
    image: elasticsearch:7.17.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - elastic
    ports:
      - "9200:9200" # to be used by direct http connections
      - "9300:9300" # to be used by application client connections
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    
  ##################################################################################
  # LOGSTASH NODE                                                                  #
  ##################################################################################
  logstash:
    image: logstash:7.17.1
    container_name: logstash
    depends_on:
      - elasticsearch
    environment:
      discovery.seed_hosts: logstash
      LS_JAVA_OPTS: "-Xms512m -Xmx512m"
    volumes:
      - ./logstash/conf:/usr/share/logstash/pipeline
      #- ./logstash/templates:/usr/share/logstash/templates
    networks:
      - elastic
    ports:
      - "5000:5000/tcp"
      - "5000:5000/udp"
      - "5044:5044"
      - "9600:9600"
  
  ##################################################################################
  # KIBANA NODE TO VISUALIZE DATA                                                  #
  ##################################################################################
  kibana:
    image: kibana:7.17.1
    container_name: kibana
    networks:
      - elastic
    ports:
      - "5601:5601"
  
  ##################################################################################
  # FILEBEAT NODE                                                                  #
  ##################################################################################
  filebeat:
    image: elastic/filebeat:7.17.1
    container_name: filebeat
    depends_on:
      - logstash
      - elasticsearch
      - kibana
    user: root
    networks:
      - elastic
    volumes:
      - ./filebeat/logs:/usr/share/filebeat/logs
      - ./filebeat/conf/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - ./filebeat/conf/filebeat_user:/etc/sysconfig/filebeat:ro
      - /var/log/syslog:/var/log/syslog:ro
      - /var/log/auth.log:/var/log/auth.log:ro
    command: ["--strict.perms=false"]
        # - "–-strict.perms=false"
        # - "–-E filebeat.config.modules.path=./modules.d/*.yml"
    stdin_open: true # docker run -i
    tty: true        # docker run -t   
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "50"
        
#################################################################################
# NETWORKS                                                                       #
##################################################################################
# Default network will be started
networks:
  elastic:
    driver: bridge
