version: "3"

services:
  ##################################################################################
  # ZOOKEEPER - KAKFA CONTROL                                                      #
  ##################################################################################
  zookeeper:
    image: zookeeper:latest
    hostname: zookeeper
    container_name: zookeeper
    networks:
      - elastic
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_SERVER_ID=1
      - ZOOKEEPER_CLIENT_PORT=2181
      #- ZOO_SERVERS: server.1=zookeeper:2888:3888
    volumes:
      - /tmp/zookeeper/data:/data
      - /tmp/zookeeper/datalog:/datalog
      - ./zookeeper/conf/zoo.cfg:/conf/zoo.cfg
      
  ##################################################################################
  # KAFKA MAIN BROKER PROCESSOR                                                    #
  ##################################################################################
  kafka:
    image: confluentinc/cp-kafka:latest
    hostname: broker
    container_name: broker
    networks:
      - elastic
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      #- KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      #- KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=LISTENER_DOCKER_INTERNAL://broker:19092,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=LISTENER_DOCKER_INTERNAL
      - KAFKA_LOG4J_LOGGERS="kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"

    volumes:
      - /tmp/kafka/data:/var/lib/kafka/data
      - ./tests:/usr/bin/tests
    depends_on:
      - zookeeper  
  
#################################################################################
# NETWORKS                                                                       #
##################################################################################
# Default network will be started
networks:
  elastic:
    driver: bridge
